import React, { useState, useEffect, useMemo } from 'react';
import DashboardLayout from './DashboardLayout';
import { apiRequest, downloadFile } from '../../lib/api';
import './AdminReports.css';

const AdminReports = () => {
  const [selectedReportModal, setSelectedReportModal] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // --- STATE MANAGEMENT ---
  const [stats, setStats] = useState({ total: 0, thisMonth: 0, mostDownloaded: '', downloads: 0, scheduled: 0 });
  const [categories, setCategories] = useState([]);
  const [reportList, setReportList] = useState([]);
  const [scheduledReports, setScheduledReports] = useState([]);
  const [recentExports, setRecentExports] = useState([]);
  const [alerts, setAlerts] = useState([]);

  const [filters, setFilters] = useState({
    category: 'All Categories', startDate: '', endDate: '', generatedBy: 'All Users', format: 'All Formats', search: ''
  });

  const fetchReportData = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await apiRequest("/api/admin/reports");
      setStats(data.stats || { total: 0, thisMonth: 0, mostDownloaded: 'Stock Summary Report', downloads: 0, scheduled: 0 });
      setCategories(data.categories || []);
      setReportList(data.reportList || []);
      setScheduledReports(data.scheduledReports || []);
      setRecentExports(data.recentExports || []);
      setAlerts(data.alerts || []);
    } catch (err) {
      setError(err.message || "Failed to load reports");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReportData();
  }, []);

  const handleFilterChange = (e) => setFilters(prev => ({ ...prev, [e.target.name]: e.target.value }));
  const resetFilters = () => setFilters({ category: 'All Categories', startDate: '', endDate: '', generatedBy: 'All Users', format: 'All Formats', search: '' });

  return (
    <DashboardLayout title="Reports">
      
      {/* 1. TOP SUMMARY CARDS */}
      <div className="reports-stats-grid">
        <div className="glass-panel stat-box">
          <div className="stat-top">Total Reports Generated <div className="stat-icon icon-blue">📄</div></div>
          <h3 className="stat-val">{stats.total}</h3>
          <span className="stat-sub text-blue">All time</span>
        </div>
        <div className="glass-panel stat-box">
          <div className="stat-top">Reports This Month <div className="stat-icon icon-green">📅</div></div>
          <h3 className="stat-val">{stats.thisMonth}</h3>
          <span className="stat-sub text-green">May 2025</span>
        </div>
        <div className="glass-panel stat-box">
          <div className="stat-top">Most Downloaded Report <div className="stat-icon icon-orange">🔥</div></div>
          <h3 className="stat-val" style={{fontSize: '1.2rem'}}>{stats.mostDownloaded}</h3>
          <span className="stat-sub text-orange">Downloaded {stats.downloads} times</span>
        </div>
        <div className="glass-panel stat-box">
          <div className="stat-top">Scheduled Reports <div className="stat-icon icon-blue">⏱️</div></div>
          <h3 className="stat-val">{stats.scheduled}</h3>
          <span className="stat-sub text-blue">Active schedules</span>
        </div>
      </div>

      {/* 2. FILTERS */}
      <div className="glass-panel" style={{ marginTop: '1.5rem' }}>
        <div className="filters-container" style={{ marginBottom: 0 }}>
          <div className="filter-group">
            <label>Report Category</label>
            <select name="category" value={filters.category} onChange={handleFilterChange} className="filter-input">
              <option>All Categories</option><option>Inventory Reports</option><option>Stock Reports</option>
            </select>
          </div>
          <div className="filter-group hide-mobile">
            <label>Date Range</label>
            <div style={{ display: 'flex', gap: '5px' }}>
              <input type="date" name="startDate" value={filters.startDate} onChange={handleFilterChange} className="filter-input" />
              <span style={{color: '#94A3B8', alignSelf: 'center'}}>-</span>
              <input type="date" name="endDate" value={filters.endDate} onChange={handleFilterChange} className="filter-input" />
            </div>
          </div>
          <div className="filter-group hide-mobile">
            <label>Generated By</label>
            <select name="generatedBy" value={filters.generatedBy} onChange={handleFilterChange} className="filter-input">
              <option>All Users</option><option>Admin</option><option>System</option>
            </select>
          </div>
          <div className="filter-group hide-mobile">
            <label>Format</label>
            <select name="format" value={filters.format} onChange={handleFilterChange} className="filter-input">
              <option>All Formats</option><option>PDF</option><option>Excel</option>
            </select>
          </div>
          <div className="filter-group">
            <label>Search Reports</label>
            <div style={{display: 'flex', gap: '10px'}}>
              <input type="text" name="search" value={filters.search} onChange={handleFilterChange} className="filter-input" placeholder="Search by report name..." />
              <button className="btn-primary" onClick={fetchReportData}>Filter</button>
              <button className="btn-secondary" onClick={resetFilters}>Reset</button>
            </div>
          </div>
        </div>
      </div>

      {/* 3. REPORT CATEGORIES & ACTIONS */}
      <div className="glass-panel" style={{ marginTop: '1.5rem' }}>
        <div className="table-header-actions" style={{ justifyContent: 'space-between', marginBottom: '0' }}>
          <h3 className="panel-header" style={{ margin: 0 }}>Report Categories</h3>
          <div className="filter-actions">
            <button className="btn-primary" onClick={() => downloadFile("/api/reports/inventory-summary/download", "Inventory_Summary.pdf")}>➕ Generate New Report</button>
            <button className="btn-secondary" style={{color: '#10b981', borderColor: 'rgba(16, 185, 129, 0.3)'}} onClick={() => downloadFile("/api/reports/stock-movement/download", "Stock_Movement.pdf")}>📥 Export Stock Report</button>
            <button className="btn-secondary" onClick={() => window.print()}>🖨️ Print</button>
          </div>
        </div>
        <div className="reports-categories-grid">
          {categories.map(cat => (
            <div className="report-cat-card" key={cat.id}>
              <div className={`cat-icon ${cat.bg}`}>{cat.icon}</div>
              <div className="cat-info">
                <h4>{cat.name}</h4>
                <p>{cat.count} Reports</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 4. MAIN SPLIT LAYOUT (60/40) */}
      <div className="reports-main-split">
        
        {/* LEFT COLUMN: Main Reports Table */}
        <div className="reports-left-col glass-panel">
          <h3 className="panel-header">Report List</h3>
          <div className="table-responsive">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Report Name</th>
                  <th className="hide-mobile">Category</th>
                  <th className="hide-mobile">Date Range</th>
                  <th>Generated On</th>
                  <th className="hide-mobile">Generated By</th>
                  <th>Format</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading ? <tr><td colSpan="7" style={{textAlign: 'center'}}>Loading...</td></tr> : 
                  reportList.map(report => (
                  <tr key={report.id}>
                    <td style={{color: '#00B4D8', fontWeight: '600', fontSize: '0.85rem'}}>📄 {report.name}</td>
                    <td className="hide-mobile" style={{fontSize: '0.8rem'}}>{report.category}</td>
                    <td className="hide-mobile" style={{fontSize: '0.8rem'}}>{report.dateRange}</td>
                    <td style={{fontSize: '0.8rem'}}>{report.generatedOn}</td>
                    <td className="hide-mobile" style={{fontSize: '0.8rem'}}>{report.generatedBy}</td>
                    <td style={{fontSize: '0.85rem', fontWeight: 'bold'}} className={report.format === 'PDF' ? 'text-red' : 'text-green'}>{report.format}</td>
                    <td>
                      <div className="table-icons">
                        <button className="icon-btn" title="View" onClick={() => setSelectedReportModal(report)}>👁️</button>
                        <button className="icon-btn" title="Download" onClick={() => {
                          const endpoint = report.name.toLowerCase().includes("expiry") ? "/api/reports/expiry-summary/download" :
                                           report.name.toLowerCase().includes("purchase") ? "/api/reports/purchase-orders/download" :
                                           report.name.toLowerCase().includes("stock") ? "/api/reports/stock-movement/download" :
                                           "/api/reports/inventory-summary/download";
                          downloadFile(endpoint, `${report.name.replaceAll(' ', '_')}.pdf`);
                        }}>📥</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="pagination-container">
            <div>Showing 1 to {reportList.length} of {stats.total} entries</div>
          </div>
        </div>

        {/* RIGHT COLUMN: Previews & Scheduled */}
        <div className="reports-right-col">
          
          <div className="glass-panel">
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem'}}>
              <h3 className="panel-header" style={{margin: 0}}>Report Preview / Summary</h3>
            </div>
            <select className="filter-input" style={{width: '100%', marginBottom: '1rem'}}>
              <option>Stock Summary Report</option>
            </select>
            
            <div className="preview-metrics">
              <div className="preview-metric-box"><p>Total Reports</p><h4>{stats.total}</h4></div>
              <div className="preview-metric-box"><p>This Month</p><h4>{stats.thisMonth}</h4></div>
              <div className="preview-metric-box"><p>Downloads</p><h4>{stats.downloads}</h4></div>
              <div className="preview-metric-box"><p>Active Schedules</p><h4>{stats.scheduled}</h4></div>
            </div>

            <h4 style={{fontSize: '0.85rem', color: '#CAF0F8', marginBottom: '10px'}}>Active Report Types</h4>
            <div style={{ padding: '10px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <span style={{ color: '#00B4D8' }}>📦 Inventory Valuation</span>
                <span style={{ color: '#10B981' }}>Ready</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <span style={{ color: '#F59E0B' }}>⏳ Expiry Analysis</span>
                <span style={{ color: '#10B981' }}>Ready</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <span style={{ color: '#3B82F6' }}>🛒 Purchase Order Summary</span>
                <span style={{ color: '#10B981' }}>Ready</span>
              </div>
            </div>
            <button className="btn-primary" style={{width: '100%', justifyContent: 'center', marginTop: '1rem'}} onClick={() => downloadFile("/api/reports/inventory-summary/download", "Inventory_Summary.pdf")}>Download Inventory Report</button>
          </div>

          <div className="glass-panel">
            <h3 className="panel-header">Scheduled Reports</h3>
            <div className="table-responsive" style={{marginBottom: 0}}>
              <table className="data-table" style={{minWidth: '200px'}}>
                <thead><tr><th>Report Name</th><th>Frequency</th><th>Next Run</th><th>Status</th></tr></thead>
                <tbody>
                  {loading ? <tr><td colSpan="4">Loading...</td></tr> : scheduledReports.map(sr => (
                    <tr key={sr.id}>
                      <td style={{fontSize: '0.8rem'}}>{sr.name}</td>
                      <td style={{fontSize: '0.8rem'}}>{sr.freq}</td>
                      <td style={{fontSize: '0.8rem'}}>{sr.nextRun}</td>
                      <td className="text-green" style={{fontSize: '0.8rem'}}>{sr.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="glass-panel">
            <h3 className="panel-header">Recent Exports</h3>
            <div className="table-responsive" style={{marginBottom: 0}}>
              <table className="data-table" style={{minWidth: '200px'}}>
                <thead><tr><th>Report Name</th><th>Exported On</th><th>Format</th><th>Download</th></tr></thead>
                <tbody>
                  {loading ? <tr><td colSpan="4">Loading...</td></tr> : recentExports.map(ex => (
                    <tr key={ex.id}>
                      <td style={{fontSize: '0.8rem'}}>{ex.name}</td>
                      <td style={{fontSize: '0.8rem'}} className="hide-mobile">{ex.date}</td>
                      <td style={{fontSize: '0.8rem', fontWeight: 'bold'}} className={ex.format === 'PDF' ? 'text-red' : 'text-green'}>{ex.format}</td>
                      <td><button className="icon-btn" title="Download" style={{fontSize: '0.8rem'}} onClick={() => downloadFile("/api/reports/inventory-summary/download", `${ex.name}.pdf`)}>📥</button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </div>

      {/* 5. BOTTOM ALERTS ROW */}
      <div className="reports-alerts-row">
        {loading ? <div>Loading alerts...</div> : alerts.map(alert => (
          <div className={`report-alert-card ${alert.type}`} key={alert.id}>
            <div style={{fontSize: '1.2rem'}}>{alert.icon}</div>
            <div className="report-alert-info">
              <h4 className={`text-${alert.type}`}>{alert.title}</h4>
              <p>{alert.desc}</p>
              <a href="#">View Report</a>
            </div>
          </div>
        ))}
      </div>

    
      {/* VIEW REPORT DETAILS MODAL */}
      {selectedReportModal && (
        <div className="modal-overlay" style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999 }}>
          <div className="glass-panel" style={{ width: '90%', maxWidth: '480px', padding: '24px', background: '#0a192f', border: '1px solid #1e3a5f', borderRadius: '12px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.2rem', borderBottom: '1px solid #1e3a5f', paddingBottom: '12px' }}>
              <h3 style={{ margin: 0, color: '#00B4D8' }}>Report Summary</h3>
              <button onClick={() => setSelectedReportModal(null)} style={{ background: 'none', border: 'none', color: '#94A3B8', fontSize: '1.2rem', cursor: 'pointer' }}>✕</button>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '12px', fontSize: '0.85rem' }}>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>Report Title</span><strong style={{ color: '#CAF0F8' }}>{selectedReportModal.name}</strong></div>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>Category</span><strong style={{ color: '#CAF0F8' }}>{selectedReportModal.category}</strong></div>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>Date Range</span><strong style={{ color: '#CAF0F8' }}>{selectedReportModal.dateRange}</strong></div>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>Generated On</span><strong style={{ color: '#CAF0F8' }}>{selectedReportModal.generatedOn}</strong></div>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>Generated By</span><strong style={{ color: '#CAF0F8' }}>{selectedReportModal.generatedBy}</strong></div>
              <div><span style={{ color: '#94A3B8', display: 'block' }}>File Format</span><strong style={{ color: selectedReportModal.format === 'PDF' ? '#f43f5e' : '#4ade80' }}>{selectedReportModal.format}</strong></div>
            </div>
            <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
              <button className="btn-secondary" onClick={() => setSelectedReportModal(null)}>Close</button>
              <button className="btn-primary" onClick={() => {
                const endpoint = selectedReportModal.name.toLowerCase().includes("expiry") ? "/api/reports/expiry-summary/download" :
                                 selectedReportModal.name.toLowerCase().includes("purchase") ? "/api/reports/purchase-orders/download" :
                                 selectedReportModal.name.toLowerCase().includes("stock") ? "/api/reports/stock-movement/download" :
                                 "/api/reports/inventory-summary/download";
                downloadFile(endpoint, `${selectedReportModal.name.replaceAll(' ', '_')}.pdf`);
              }}>📥 Download</button>
            </div>
          </div>
        </div>
      )}

    </DashboardLayout>
  );
};

export default AdminReports;