package com.v.medical.entity;

public enum AuditAction {
    STOCK_ADJUSTMENT,
    STOCK_IN,
    STOCK_OUT,
    PRICE_UPDATE,
    BATCH_EXPIRY_OVERRIDE,
    PURCHASE_ORDER_CREATE,
    PURCHASE_ORDER_STATUS,
    PURCHASE_ORDER_RECEIVE,
    WARD_TRANSFER_REQUEST,
    WARD_TRANSFER_APPROVE,
    WARD_TRANSFER_DISPATCH,
    WARD_TRANSFER_RECEIVE,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    SYSTEM_CONFIG_CHANGE,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    AUTO_REORDER_TRIGGER
}
