package com.v.medical.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "reports")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Report {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ==========================================
    // REPORT NAME
    // ==========================================

    @Column(nullable = false, length = 200)
    private String reportName;

    // ==========================================
    // TYPE
    // ==========================================

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private ReportType reportType;

    // ==========================================
    // FORMAT
    // ==========================================

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ReportFormat format;

    // ==========================================
    // STATUS
    // ==========================================

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private ReportStatus status =
            ReportStatus.GENERATING;

    // ==========================================
    // DATE RANGE
    // ==========================================

    private LocalDate fromDate;

    private LocalDate toDate;

    // ==========================================
    // GENERATED BY
    // ==========================================

    @Column(length = 150)
    private String generatedBy;

    // ==========================================
    // FILE
    // ==========================================

    @Column(length = 500)
    private String fileName;

    @Column(length = 1000)
    private String filePath;

    private Long fileSize;

    // ==========================================
    // FAVORITE
    // ==========================================

    @Column(nullable = false)
    private boolean favorite = false;

    // ==========================================
    // ERROR
    // ==========================================

    @Column(length = 2000)
    private String errorMessage;

    // ==========================================
    // AUDIT
    // ==========================================

    @Column(nullable = false)
    private LocalDateTime generatedAt;

    private LocalDateTime completedAt;

    // ==========================================
    // CONSTRUCTOR
    // ==========================================

    public Report() {
        this.generatedAt =
                LocalDateTime.now();
    }

    // ==========================================
    // GETTERS
    // ==========================================

    public Long getId() {
        return id;
    }

    public String getReportName() {
        return reportName;
    }

    public ReportType getReportType() {
        return reportType;
    }

    public ReportFormat getFormat() {
        return format;
    }

    public ReportStatus getStatus() {
        return status;
    }

    public LocalDate getFromDate() {
        return fromDate;
    }

    public LocalDate getToDate() {
        return toDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public String getFileName() {
        return fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public boolean isFavorite() {
        return favorite;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    // ==========================================
    // SETTERS
    // ==========================================

    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public void setReportType(
            ReportType reportType) {
        this.reportType = reportType;
    }

    public void setFormat(
            ReportFormat format) {
        this.format = format;
    }

    public void setStatus(
            ReportStatus status) {
        this.status = status;
    }

    public void setFromDate(
            LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public void setToDate(
            LocalDate toDate) {
        this.toDate = toDate;
    }

    public void setGeneratedBy(
            String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public void setFileName(
            String fileName) {
        this.fileName = fileName;
    }

    public void setFilePath(
            String filePath) {
        this.filePath = filePath;
    }

    public void setFileSize(
            Long fileSize) {
        this.fileSize = fileSize;
    }

    public void setFavorite(
            boolean favorite) {
        this.favorite = favorite;
    }

    public void setErrorMessage(
            String errorMessage) {
        this.errorMessage =
                errorMessage;
    }

    public void setCompletedAt(
            LocalDateTime completedAt) {
        this.completedAt =
                completedAt;
    }

    public void setGeneratedAt(
            LocalDateTime generatedAt) {
        this.generatedAt =
                generatedAt;
    }
}