package com.v.medical.Service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;

@Component
public class PdfReportGenerator {

    public byte[] generate(
            String title,
            String generatedBy,
            List<Map<String, Object>> rows) {

        try {

            ByteArrayOutputStream output =
                    new ByteArrayOutputStream();

            Document document =
                    new Document(
                            PageSize.A4
                    );

            PdfWriter.getInstance(
                    document,
                    output
            );

            document.open();

            // ==================================
            // TITLE
            // ==================================

            Font titleFont =
                    FontFactory.getFont(
                            FontFactory.HELVETICA_BOLD,
                            20
                    );

            Paragraph titleParagraph =
                    new Paragraph(
                            title,
                            titleFont
                    );

            titleParagraph.setAlignment(
                    Element.ALIGN_CENTER
            );

            document.add(
                    titleParagraph
            );

            document.add(
                    new Paragraph(
                            "MediStock"
                    )
            );

            document.add(
                    new Paragraph(
                            "Generated By: "
                                    + generatedBy
                    )
            );

            document.add(
                    new Paragraph(
                            " "
                    )
            );

            // ==================================
            // NO DATA
            // ==================================

            if (rows == null ||
                    rows.isEmpty()) {

                document.add(
                        new Paragraph(
                                "No data available."
                        )
                );

                document.close();

                return output.toByteArray();
            }

            // ==================================
            // TABLE
            // ==================================

            Map<String, Object> firstRow =
                    rows.get(0);

            PdfPTable table =
                    new PdfPTable(
                            firstRow.size()
                    );

            table.setWidthPercentage(100);

            // Headers

            for (String key :
                    firstRow.keySet()) {

                table.addCell(
                        new Phrase(
                                key
                        )
                );
            }

            // Data

            for (Map<String, Object> row :
                    rows) {

                for (String key :
                        firstRow.keySet()) {

                    Object value =
                            row.get(key);

                    table.addCell(
                            new Phrase(
                                    value == null
                                            ? ""
                                            : String.valueOf(
                                                    value
                                            )
                            )
                    );
                }
            }

            document.add(table);

            document.add(
                    new Paragraph(
                            " "
                    )
            );

            document.add(
                    new Paragraph(
                            "Generated by MediStock"
                    )
            );

            document.close();

            return output.toByteArray();

        } catch (Exception e) {

            throw new RuntimeException(
                    "PDF generation failed",
                    e
            );
        }
    }
}